apiVersion: v1
kind: Namespace
metadata:
  name: mt-helper
spec: {}

---
apiVersion: v1
kind: Secret
metadata:
  name: mt-helper
  namespace: mt-helper
data:
  MTORRENT_ENDPOINT: ""
  MTORRENT_SECRETKEY: ""
  TELEGRAM_BOT_TOKEN: ""
  TELEGRAM_CHANNEL_ID: ""

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mt-helper
  name: mt-helper
  namespace: mt-helper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mt-helper
  strategy: {}
  template:
    metadata:
      labels:
        app: mt-helper
    spec:
      containers:
      - image: mt-helper:latest
        name: mt-helper
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 64Mi
        envFrom:
        - secretRef:
            name: mt-helper
